version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  chatbot:
    build: .
    container_name: llama_chatbot
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  ollama_data:
